# Generated by Django 2.2.5 on 2019-09-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notification_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='list',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.Marker'),
        ),
    ]
