# Generated by Django 2.2.5 on 2019-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190925_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notification_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
