# Generated by Django 2.2.5 on 2019-09-25 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_auto_20190925_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ToDoList',
        ),
    ]
