# Generated by Django 2.2.5 on 2019-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('todolist', '0006_auto_20191001_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
